<a href="https://colab.research.google.com/github/Irtisam99/Deep_Learning/blob/main/Deep_Learning_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
X=np.array(
    [
        [0.0,0.0],
        [0.0,1.0],
        [1.0,0.0],
        [1.0,1.0]
    ]
)
print(X)
print(type(X))

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
<class 'numpy.ndarray'>


In [3]:
X=torch.tensor(X)
print(X)
print(type(X))

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>


In [4]:
np.random.rand(5)

array([0.42327593, 0.95628928, 0.80664251, 0.56565229, 0.81597458])

In [5]:
my_tensor=torch.rand(5)
print(my_tensor)

tensor([0.4927, 0.4992, 0.2316, 0.1977, 0.5769])


In [6]:
my_tensor.sum(axis=0)

tensor(1.9981)

In [7]:
torch.randn(3)

tensor([-0.4709, -0.2156,  0.0774])

In [8]:
"""Parameter
"""
nn.Parameter(torch.randn(3))

Parameter containing:
tensor([0.7934, 0.0643, 0.1808], requires_grad=True)

In [9]:
"""
X = [x1, x2, x3]
W = [w1, w2, w3]
b
y_pred = x1 * w1 + x2 * w2 + x3 * w3 + b // linear or nonlinear? -> linear
- linear equation can not detect nonlinear patterns
- ax^2 + bx + c is non linear equation of degree 2
- ax^3 + bx^2 + cx + d is non linear equation of degree 3

Increasing nonlinearity means increasing model complexity
Increasing model complexity model will learn better non-linearity

y_pred = Non linear Activation function(x1 * w1 + x2 * w2 + x3 * w3 + b)
"""
class Perceptron(nn.Module):
  def __init__(self,input_size):
    super(Perceptron,self).__init__()
    self.input_size=input_size

    self.weight=nn.Parameter(torch.randn(input_size))
    self.bias=nn.Parameter(torch.zeros(1))
    print(self.weight,self.bias)

  def forward(self,x):
    z=x @ self.weight+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

perceptron=Perceptron(3)

Parameter containing:
tensor([-0.6967,  0.3165, -0.9470], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [11]:
import os

model_path="/content/drive/MyDrive/BongoDev/perceptron.pth"
model=Perceptron(3)

if os.path.exists(model_path):
  model.load_state_dict(torch.load(model_path))
  print("Model Loaded")

Parameter containing:
tensor([-0.6201, -0.4382, -0.0346], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)
Model Loaded


In [12]:
x=torch.randn(3)
print(x)

tensor([ 1.3324, -1.8347,  0.1216])


In [13]:
y_pred=model(x)
print(y_pred)

tensor([0.0219], grad_fn=<SigmoidBackward0>)


In [14]:
print(*model.parameters())

Parameter containing:
tensor([1.0637, 1.0637, 4.4147], requires_grad=True) Parameter containing:
tensor([-3.8030], requires_grad=True)


In [15]:
"""
Cost Function
"""
criterion=nn.BCELoss() # Binary cross entropy loss

""" Optimizers """
optimizer=torch.optim.Adam(
    model.parameters(),
    lr=0.0001

)

In [16]:
X = torch.Tensor(
    [
        [0.0, 0.0, 0.0], # sample input 1 (x1, x2, x3)
        [0.0, 1.0, 0.0], # sample input 2
        [1.0, 0.0, 0.0], # sample input 3
        [1.0, 1.0, 1.0]  # sample input 4
    ]
)

Y = torch.Tensor(
    [
        [0.0], # sample output 1
        [0.0], # sample output 2
        [0.0], # sample output 3
        [1.0]  # sample output 4
    ]
)

In [17]:
y_preds=model(X)
print(y_preds.shape)

torch.Size([4])


In [18]:
print(y_preds)

tensor([0.0218, 0.0607, 0.0607, 0.9393], grad_fn=<SigmoidBackward0>)


In [19]:
y_preds.ndim

1

In [20]:
y_preds=y_preds.unsqueeze(axis=1)
print(y_preds.shape)
print(y_preds)

torch.Size([4, 1])
tensor([[0.0218],
        [0.0607],
        [0.0607],
        [0.9393]], grad_fn=<UnsqueezeBackward0>)


In [21]:
y_preds.ndim

2

In [22]:
def train_model(model,epochs):
  for epoch in range(epochs):
    """Prediction: Forward propagation"""
    y_preds=model(X)

    """Loss Calculation"""
    loss=criterion(y_preds.unsqueeze(axis=1),Y)

    """ Calculate gradient"""
    optimizer.zero_grad()
    loss.backward() # Backpropagation

    """ Update weight"""
    optimizer.step()

    if epoch % 1000 ==0:
      print(f"Epoch:{epoch},Loss:{loss.item():.4f}")

In [23]:
train_model(model,20000)

Epoch:0,Loss:0.0525
Epoch:1000,Loss:0.0491
Epoch:2000,Loss:0.0459
Epoch:3000,Loss:0.0431
Epoch:4000,Loss:0.0404
Epoch:5000,Loss:0.0379
Epoch:6000,Loss:0.0355
Epoch:7000,Loss:0.0333
Epoch:8000,Loss:0.0313
Epoch:9000,Loss:0.0293
Epoch:10000,Loss:0.0275
Epoch:11000,Loss:0.0258
Epoch:12000,Loss:0.0242
Epoch:13000,Loss:0.0227
Epoch:14000,Loss:0.0213
Epoch:15000,Loss:0.0200
Epoch:16000,Loss:0.0188
Epoch:17000,Loss:0.0176
Epoch:18000,Loss:0.0165
Epoch:19000,Loss:0.0155


In [24]:
print(*model.parameters())

Parameter containing:
tensor([1.6821, 1.6821, 6.3034], requires_grad=True) Parameter containing:
tensor([-5.6749], requires_grad=True)


In [25]:
"""Mode of a torch model

By default: Train
We can set the mode to eval during prediction
"""
def predict(model,X):
  model.eval()
  with torch.no_grad():
    test_model=model(X)
  return test_model

predict(model,X)

tensor([0.0034, 0.0181, 0.0181, 0.9819])

In [26]:
Y

tensor([[0.],
        [0.],
        [0.],
        [1.]])

In [27]:
model.state_dict()

OrderedDict([('weight', tensor([1.6821, 1.6821, 6.3034])),
             ('bias', tensor([-5.6749]))])

In [28]:
torch.save(model.state_dict(),model_path)