<a href="https://colab.research.google.com/github/Irtisam99/Deep_Learning/blob/main/Deep_Learning_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import torch
import torch.nn as nn
import numpy as np

In [20]:
X=np.array(
    [
        [0.0,0.0],
        [0.0,1.0],
        [1.0,0.0],
        [1.0,1.0]
    ]
)
print(X)
print(type(X))

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
<class 'numpy.ndarray'>


In [21]:
X=torch.tensor(X)
print(X)
print(type(X))

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>


In [22]:
np.random.rand(5)

array([0.57612565, 0.19636823, 0.84241246, 0.52838486, 0.46976319])

In [23]:
my_tensor=torch.rand(5)
print(my_tensor)

tensor([0.4953, 0.5837, 0.1244, 0.7491, 0.2747])


In [24]:
my_tensor.sum(axis=0)

tensor(2.2271)

In [25]:
torch.randn(3)

tensor([ 0.1519,  0.8746, -1.6120])

In [26]:
"""Parameter
"""
nn.Parameter(torch.randn(3))

Parameter containing:
tensor([-1.5266, -1.9387, -1.7774], requires_grad=True)

In [28]:
"""
X = [x1, x2, x3]
W = [w1, w2, w3]
b
y_pred = x1 * w1 + x2 * w2 + x3 * w3 + b // linear or nonlinear? -> linear
- linear equation can not detect nonlinear patterns
- ax^2 + bx + c is non linear equation of degree 2
- ax^3 + bx^2 + cx + d is non linear equation of degree 3

Increasing nonlinearity means increasing model complexity
Increasing model complexity model will learn better non-linearity

y_pred = Non linear Activation function(x1 * w1 + x2 * w2 + x3 * w3 + b)
"""
class Perceptron(nn.Module):
  def __init__(self,input_size):
    super(Perceptron,self).__init__()
    self.input_size=input_size

    self.weight=nn.Parameter(torch.randn(input_size))
    self.bias=nn.Parameter(torch.zeros(1))
    print(self.weight,self.bias)

  def forward(self,x):
    z=x @ self.weight+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

perceptron=Perceptron(3)

Parameter containing:
tensor([ 0.1516, -0.1491,  0.0499], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [29]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [35]:
import os

model_path="/content/drive/MyDrive/BongoDev/perceptron.pth"
model=Perceptron(3)

if os.path.exists(model_path):
  model.load_state_dict(torch.load(model_path))
  print("Model Loaded")

Parameter containing:
tensor([ 0.4748, -2.3362,  0.5030], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [36]:
x=torch.randn(3)
print(x)

tensor([ 0.7677, -0.7000,  0.5230])


In [37]:
y_pred=model(x)
print(y_pred)

tensor([0.9058], grad_fn=<SigmoidBackward0>)
